start-at-login = true

after-startup-command = ['exec-and-forget brew services start borders']

[workspace-to-monitor-force-assignment]
1 = 'main'
2 = 'main'
3 = 'main'
4 = 'secondary'
5 = 'secondary'

[gaps]
inner.horizontal = 0
inner.vertical   = 0
outer.left       = 6
outer.bottom     = 6
outer.top        = 6
outer.right      = 6

[mode.main.binding]
# Focus
cmd-alt-h = 'focus left'
cmd-alt-j = 'focus down'
cmd-alt-k = 'focus up'
cmd-alt-l = 'focus right'

# Move
cmd-alt-shift-h = 'move left'
cmd-alt-shift-j = 'move down'
cmd-alt-shift-k = 'move up'
cmd-alt-shift-l = 'move right'

# Resize
cmd-alt-minus = 'resize smart -50'
cmd-alt-equal = 'resize smart +50'

# Workspaces
cmd-alt-1 = 'workspace 1'
cmd-alt-2 = 'workspace 2'
cmd-alt-3 = 'workspace 3'
cmd-alt-4 = 'workspace 4'
cmd-alt-5 = 'workspace 5'

cmd-alt-shift-1 = 'move-node-to-workspace 1'
cmd-alt-shift-2 = 'move-node-to-workspace 2'
cmd-alt-shift-3 = 'move-node-to-workspace 3'
cmd-alt-shift-4 = 'move-node-to-workspace 4'
cmd-alt-shift-5 = 'move-node-to-workspace 5'

# Layout
cmd-alt-f = 'fullscreen'
cmd-alt-shift-space = 'layout floating tiling'

# Reload
cmd-alt-shift-r = 'reload-config'
